# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/fewsats',
                'doc_host': 'https://fewsats.github.io',
                'git_url': 'https://github.com/fewsats/fewsats-python',
                'lib_path': 'fewsats'},
  'syms': { 'fewsats.core': { 'fewsats.core.Fewsats': ('core.html#fewsats', 'fewsats/core.py'),
                              'fewsats.core.Fewsats.__init__': ('core.html#fewsats.__init__', 'fewsats/core.py'),
                              'fewsats.core.Fewsats._request': ('core.html#fewsats._request', 'fewsats/core.py'),
                              'fewsats.core.Fewsats.get_payment_methods': ('core.html#fewsats.get_payment_methods', 'fewsats/core.py'),
                              'fewsats.core.Fewsats.preview_purchase': ('core.html#fewsats.preview_purchase', 'fewsats/core.py'),
                              'fewsats.core.Fewsats.purchase': ('core.html#fewsats.purchase', 'fewsats/core.py')}}}
